services:
  - type: web
    name: printiva-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: true
